### ISSUE TITLE
Some IP addresses leads to crash

### ISSUE THREAD

**Issue by apristen** [leafo/luajit-geoip#2]
Here's a log of IP resolution which leads to crash:

```
localhost:9001> tmp_mmdb = require('geoip.mmdb').load_database('data/GeoLite2-City.mmdb')
---
...

localhost:9001> tmp_mmdb:lookup("212.237.134.97")
---
- error: '/usr/local/share/lua/5.1/geoip/mmdb.lua:217: bad argument #2 to ''assert''
    (string expected, got cdata)'
...
```

While online GeoIP2 maxmind database resolves the IP fine:
https://www.maxmind.com/en/geoip-demo?js-geoip-demo__addresses=212.237.134.97

Another IP example which leads to crash:
```
localhost:9001> tmp_mmdb:lookup("116.202.84.109")
---
- error: '/usr/local/share/lua/5.1/geoip/mmdb.lua:217: bad argument #2 to ''assert''
    (string expected, got cdata)'
...
```
Also resolved fine with online GeoIP2:
https://www.maxmind.com/en/geoip-demo?js-geoip-demo__addresses=116.202.84.109

Bug reproduced only for some IP addresses, for example most works fine:
```
localhost:9001> tmp_mmdb:lookup("8.8.8.8")
---
- location:
    accuracy_radius: 1000
    longitude: -97.822
    latitude: 37.751
    time_zone: America/Chicago
  country:
    names:
      en: United States
      zh-CN: 美国
      fr: États-Unis
      ru: США
      es: Estados Unidos
      pt-BR: Estados Unidos
      de: USA
      ja: アメリカ合衆国
    iso_code: US
    geoname_id: 6252001
  continent:
    names:
      en: North America
      zh-CN: 北美洲
      fr: Amérique du Nord
      ru: Северная Америка
      es: Norteamérica
      pt-BR: América do Norte
      de: Nordamerika
      ja: 北アメリカ
    code: NA
    geoname_id: 6255149
  registered_country:
    names:
      en: United States
      zh-CN: 美国
      fr: États-Unis
      ru: США
      es: Estados Unidos
      pt-BR: Estados Unidos
      de: USA
      ja: アメリカ合衆国
    iso_code: US
    geoname_id: 6252001
...
```

Also I try this [ https://github.com/fabled/lua-maxminddb ] and that 2 IPs resolved fine.

@leafo ,
thanks! luajit-geoip is very comfortable in installation under Tarantool DB.
Any ideas how to fix that crashes on particular IP addresses in luajit-geoip (it seems it expects string but got cdata somehow, by error logs) ?
